/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppActivityRouteImport } from './routes/_app/activity'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppCalculatorRouteImport } from './routes/_app/calculator'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppImportRouteImport } from './routes/_app/import'
import { Route as AppMoreRouteImport } from './routes/_app/more'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppAdminActivityRouteImport } from './routes/_app/admin/activity'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppConnectionsIndexRouteImport } from './routes/_app/connections/index'
import { Route as AppConnectionsConnectionIdRouteImport } from './routes/_app/connections/$connectionId'
import { Route as AppLoansIndexRouteImport } from './routes/_app/loans/index'
import { Route as AppLoansLoanIdRouteImport } from './routes/_app/loans/$loanId'
import { Route as AppSharedIndexRouteImport } from './routes/_app/shared/index'
import { Route as AppSharedLinkIdIndexRouteImport } from './routes/_app/shared/$linkId/index'
import { Route as AppSharedLinkIdLoansLoanIdRouteImport } from './routes/_app/shared/$linkId/loans/$loanId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppCalculatorRoute = AppCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminActivityRoute = AppAdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppConnectionsIndexRoute = AppConnectionsIndexRouteImport.update({
  id: '/connections/',
  path: '/connections/',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsConnectionIdRoute =
  AppConnectionsConnectionIdRouteImport.update({
    id: '/connections/$connectionId',
    path: '/connections/$connectionId',
    getParentRoute: () => AppRoute,
  } as any)
const AppLoansIndexRoute = AppLoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansLoanIdRoute = AppLoansLoanIdRouteImport.update({
  id: '/loans/$loanId',
  path: '/loans/$loanId',
  getParentRoute: () => AppRoute,
} as any)
const AppSharedIndexRoute = AppSharedIndexRouteImport.update({
  id: '/shared/',
  path: '/shared/',
  getParentRoute: () => AppRoute,
} as any)
const AppSharedLinkIdIndexRoute = AppSharedLinkIdIndexRouteImport.update({
  id: '/shared/$linkId/',
  path: '/shared/$linkId/',
  getParentRoute: () => AppRoute,
} as any)
const AppSharedLinkIdLoansLoanIdRoute =
  AppSharedLinkIdLoansLoanIdRouteImport.update({
    id: '/shared/$linkId/loans/$loanId',
    path: '/shared/$linkId/loans/$loanId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/activity': typeof AppActivityRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/calculator': typeof AppCalculatorRoute
  '/dashboard': typeof AppDashboardRoute
  '/import': typeof AppImportRoute
  '/more': typeof AppMoreRoute
  '/settings': typeof AppSettingsRoute
  '/admin/activity': typeof AppAdminActivityRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/connections/$connectionId': typeof AppConnectionsConnectionIdRoute
  '/loans/$loanId': typeof AppLoansLoanIdRoute
  '/admin/': typeof AppAdminIndexRoute
  '/connections/': typeof AppConnectionsIndexRoute
  '/loans/': typeof AppLoansIndexRoute
  '/shared/': typeof AppSharedIndexRoute
  '/shared/$linkId/': typeof AppSharedLinkIdIndexRoute
  '/shared/$linkId/loans/$loanId': typeof AppSharedLinkIdLoansLoanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/activity': typeof AppActivityRoute
  '/calculator': typeof AppCalculatorRoute
  '/dashboard': typeof AppDashboardRoute
  '/import': typeof AppImportRoute
  '/more': typeof AppMoreRoute
  '/settings': typeof AppSettingsRoute
  '/admin/activity': typeof AppAdminActivityRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/connections/$connectionId': typeof AppConnectionsConnectionIdRoute
  '/loans/$loanId': typeof AppLoansLoanIdRoute
  '/admin': typeof AppAdminIndexRoute
  '/connections': typeof AppConnectionsIndexRoute
  '/loans': typeof AppLoansIndexRoute
  '/shared': typeof AppSharedIndexRoute
  '/shared/$linkId': typeof AppSharedLinkIdIndexRoute
  '/shared/$linkId/loans/$loanId': typeof AppSharedLinkIdLoansLoanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/calculator': typeof AppCalculatorRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/import': typeof AppImportRoute
  '/_app/more': typeof AppMoreRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/admin/activity': typeof AppAdminActivityRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/connections/$connectionId': typeof AppConnectionsConnectionIdRoute
  '/_app/loans/$loanId': typeof AppLoansLoanIdRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/connections/': typeof AppConnectionsIndexRoute
  '/_app/loans/': typeof AppLoansIndexRoute
  '/_app/shared/': typeof AppSharedIndexRoute
  '/_app/shared/$linkId/': typeof AppSharedLinkIdIndexRoute
  '/_app/shared/$linkId/loans/$loanId': typeof AppSharedLinkIdLoansLoanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/activity'
    | '/admin'
    | '/calculator'
    | '/dashboard'
    | '/import'
    | '/more'
    | '/settings'
    | '/admin/activity'
    | '/admin/users'
    | '/connections/$connectionId'
    | '/loans/$loanId'
    | '/admin/'
    | '/connections/'
    | '/loans/'
    | '/shared/'
    | '/shared/$linkId/'
    | '/shared/$linkId/loans/$loanId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/activity'
    | '/calculator'
    | '/dashboard'
    | '/import'
    | '/more'
    | '/settings'
    | '/admin/activity'
    | '/admin/users'
    | '/connections/$connectionId'
    | '/loans/$loanId'
    | '/admin'
    | '/connections'
    | '/loans'
    | '/shared'
    | '/shared/$linkId'
    | '/shared/$linkId/loans/$loanId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/_app/activity'
    | '/_app/admin'
    | '/_app/calculator'
    | '/_app/dashboard'
    | '/_app/import'
    | '/_app/more'
    | '/_app/settings'
    | '/_app/admin/activity'
    | '/_app/admin/users'
    | '/_app/connections/$connectionId'
    | '/_app/loans/$loanId'
    | '/_app/admin/'
    | '/_app/connections/'
    | '/_app/loans/'
    | '/_app/shared/'
    | '/_app/shared/$linkId/'
    | '/_app/shared/$linkId/loans/$loanId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calculator': {
      id: '/_app/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof AppCalculatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/more': {
      id: '/_app/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/activity': {
      id: '/_app/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AppAdminActivityRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/connections/': {
      id: '/_app/connections/'
      path: '/connections'
      fullPath: '/connections/'
      preLoaderRoute: typeof AppConnectionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections/$connectionId': {
      id: '/_app/connections/$connectionId'
      path: '/connections/$connectionId'
      fullPath: '/connections/$connectionId'
      preLoaderRoute: typeof AppConnectionsConnectionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans/': {
      id: '/_app/loans/'
      path: '/loans'
      fullPath: '/loans/'
      preLoaderRoute: typeof AppLoansIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans/$loanId': {
      id: '/_app/loans/$loanId'
      path: '/loans/$loanId'
      fullPath: '/loans/$loanId'
      preLoaderRoute: typeof AppLoansLoanIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shared/': {
      id: '/_app/shared/'
      path: '/shared'
      fullPath: '/shared/'
      preLoaderRoute: typeof AppSharedIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shared/$linkId/': {
      id: '/_app/shared/$linkId/'
      path: '/shared/$linkId'
      fullPath: '/shared/$linkId/'
      preLoaderRoute: typeof AppSharedLinkIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shared/$linkId/loans/$loanId': {
      id: '/_app/shared/$linkId/loans/$loanId'
      path: '/shared/$linkId/loans/$loanId'
      fullPath: '/shared/$linkId/loans/$loanId'
      preLoaderRoute: typeof AppSharedLinkIdLoansLoanIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminActivityRoute: typeof AppAdminActivityRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminActivityRoute: AppAdminActivityRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppCalculatorRoute: typeof AppCalculatorRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppImportRoute: typeof AppImportRoute
  AppMoreRoute: typeof AppMoreRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppConnectionsConnectionIdRoute: typeof AppConnectionsConnectionIdRoute
  AppLoansLoanIdRoute: typeof AppLoansLoanIdRoute
  AppConnectionsIndexRoute: typeof AppConnectionsIndexRoute
  AppLoansIndexRoute: typeof AppLoansIndexRoute
  AppSharedIndexRoute: typeof AppSharedIndexRoute
  AppSharedLinkIdIndexRoute: typeof AppSharedLinkIdIndexRoute
  AppSharedLinkIdLoansLoanIdRoute: typeof AppSharedLinkIdLoansLoanIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppCalculatorRoute: AppCalculatorRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppImportRoute: AppImportRoute,
  AppMoreRoute: AppMoreRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppConnectionsConnectionIdRoute: AppConnectionsConnectionIdRoute,
  AppLoansLoanIdRoute: AppLoansLoanIdRoute,
  AppConnectionsIndexRoute: AppConnectionsIndexRoute,
  AppLoansIndexRoute: AppLoansIndexRoute,
  AppSharedIndexRoute: AppSharedIndexRoute,
  AppSharedLinkIdIndexRoute: AppSharedLinkIdIndexRoute,
  AppSharedLinkIdLoansLoanIdRoute: AppSharedLinkIdLoansLoanIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
